services:
  client:
    build:
      context: ./client
    container_name: foodxp-client
    ports:
      - "3000:3000"
    depends_on:
      - server  
  server:
    build:
      context: ./server
    container_name: foodxp-server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV = production
    volumes:
      - ./server:/app